azure:
  blob:
    container: ${BLOB_CONTAINER}
  servicebus:
    connection-string: ${SERVICEBUS_CONNECTION_STRING}
    queue:
      battery:
        endpoint:
          queue: ${BATTERY_ENDPOINT_QUEUE}
      ploting:
        endpoint:
          queue: ${PLOTING_ENDPOINT_QUEUE}
      tenant:
        endpoint:
          queue: ${TENANT_ENDPOINT_QUEUE}
  storage:
    connection-string: ${STORAGE_CONNECTION_STRING}
    sas-token: ${SAS_TOKEN}
  mail-service:
    connection-string: ${MAIL_SERVICE_CONNECTION_STRING}
    email-sender: ${MAIL_SENDER}
jwt:
  secret: ${JWT_SECRET}
  sessionTime: ${JWT_SESSION_TIME}
proxy:
  enabled: ${PROXY_ENABLED}
  host: ${PROXY-HOST}
  password: ${PC_PASSWORD}
  port: ${PORT_NUMBER}
  username: ${PC_USERNAME}
python:
  url: ${PYTHON_URL}
  account:
    username: ${PYTHON_USERNAME}
    password: ${PYTHON_PASSWORD}
spring:
  datasource:
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
        jdbc:
          lob:
            non_contextual_creation: true
template:
  emailConfirmation: ${EMAIL_CONFIRMATION}
  resetPassword: ${RESET_PASSWORD}
  resetPasswordConfirmation: ${RESET_PASSWORD_CONFIRMATION}
