export const BACKEND_API_URL = "https://ard500javaservice.azurewebsites.net/api"

export const statusTranslations: { [key: number]: string } = {
  400: 'Bad Request',
  403: 'Invalid Credentials',
  404: 'User Not Found',
  409: 'Email Already in Use',
  500: 'Internal Server Error',
};

export enum PLOT_TYPES {
  SOHC_MIN_CELL_EVOLUTION_AGAINST_TIME = "SOHC_MIN_CELL_EVOLUTION_AGAINST_TIME",
  SOHC_EQ_PARAMS_AGAINST_TIME="SOHC_EQ_PARAMS_AGAINST_TIME",
  SOHC_3_WORST_CELL_INDEX_AGAINST_TIME="SOHC_3_WORST_CELL_INDEX_AGAINST_TIME",
  SOHC_3_WORST_SOHCS_AGAINST_TIME="SOHC_3_WORST_SOHCS_AGAINST_TIME",
  CHARGE_PROFILE_PROTECTED_CURRENT_AGAINST_SOC_FOR_EACH_TEMPERATURE="CHARGE_PROFILE_PROTECTED_CURRENT_AGAINST_SOC_FOR_EACH_TEMPERATURE",
  CHARGE_PROFILE_FAST_CURRENT_AGAINST_SOC_FOR_EACH_TEMPERATURE="CHARGE_PROFILE_FAST_CURRENT_AGAINST_SOC_FOR_EACH_TEMPERATURE",
}

