"""
Django settings for PlotService project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY='django-insecure-o)ekw-4i=l==f1%$8rf$$u_j14tu7t*%n^2ccz^*!g5g#%wcqm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PlotService.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
}

WSGI_APPLICATION = 'PlotService.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

APPEND_SLASH = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


ENVIRONMENT = os.environ.get('DJANGO_ENV', 'local')

if ENVIRONMENT == 'local':
    dotenv_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env.dev')
    load_dotenv(dotenv_path)
else:
    load_dotenv()


DATABASE = {
    'default': {
        'HOST': os.environ.get('DATABASE_HOST', default='localhost'),
        'PORT': os.environ.get('DATABASE_PORT', default='5432'),
        'NAME': os.environ.get('DATABASE_NAME', default='batterydatabase'),
        'USER': os.environ.get('DATABASE_USER', default='postgres'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', default='<password>'),

    }
}
# TODO your password here

TEAMSCHANNEL_CONNECTION_URL = os.environ.get('TEAMSCHANNEL_CONNECTION_URL', default='DefaultEndpointsProtocol=https;AccountName=plottingresultsws2023;AccountKey=sPuTFb605p2k+TGXYgAiUh5VG7bN3V+bHuaqUCPIa6Q6Mfp+6beO0rlGWyRFvycrDdAugHQqTonK+ASt3dvU8Q==;EndpointSuffix=core.windows.net')


BLOBSTORAGE = {
    'default': {
        'CONNECTION_STRING': os.environ.get('BLOBSTORAGE_CONNECTION_STRING', default='DefaultEndpointsProtocol=https;AccountName=plottingresultsws2023;AccountKey=sPuTFb605p2k+TGXYgAiUh5VG7bN3V+bHuaqUCPIa6Q6Mfp+6beO0rlGWyRFvycrDdAugHQqTonK+ASt3dvU8Q==;EndpointSuffix=core.windows.net'),
        'CONTAINER': os.environ.get('BLOBSTORAGE_CONTAINER', default='plottingresultsws2023'),

    }
}


DATABRICKS = {
    'default': {
        'BASE_URL': os.environ.get('DATABRICKS_BASE_URL', default='https://adb-6999700956331769.9.azuredatabricks.net/api/2.0/dbfs'),
        'ACCESS_TOKEN': os.environ.get('DATABRICKS_ACCESS_TOKEN', default='dapi8f19b5b3cb85da6a4962295f67d2e879-2'),
        'CHARGE_PROFILES_PATH': os.environ.get('DATABRICKS_CHARGE_PROFILES_PATH', default='/FileStore/ws2023/robert.csv/part-00000-tid-1561993795163595618-844b38bb-0527-4d47-8003-248c1bc436f2-2913-1-c000.csv'),
        'SOHCS_PATH': os.environ.get('DATABRICKS_SOHCS_PATH', default='/FileStore/ws2023/robert_sohc.csv/part-00001-tid-8752186245449221241-701cde07-cb06-4fb2-aa32-939a1a18ab52-2932-1-c000.csv'),

    }
}